/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmi;

import java.rmi.Naming;
import java.rmi.RemoteException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ibyte
 */
public class Cliente extends javax.swing.JDialog {
    Servico servico = null;
    /**
     * Creates new form Cliente
     * @param parent
     * @param modal
     */
    public Cliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            String localizacao = "//localhost:1232/servico";
            servico = (Servico) Naming.lookup(localizacao);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Erro: "+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtCurso = new javax.swing.JTextField();
        btnListCandidatos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCurso = new javax.swing.JRadioButton();
        btnCidade = new javax.swing.JRadioButton();
        txtCidade = new javax.swing.JTextField();
        rButtonShowAll = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnExp = new javax.swing.JRadioButton();
        btnInfo = new javax.swing.JRadioButton();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCandidatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCursoActionPerformed(evt);
            }
        });

        btnListCandidatos.setText("Pesquisar");
        btnListCandidatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListCandidatosMouseClicked(evt);
            }
        });
        btnListCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCandidatosActionPerformed(evt);
            }
        });

        jLabel1.setText("Filtrar por:");

        buttonGroup1.add(btnCurso);
        btnCurso.setText("Curso");
        btnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnCidade);
        btnCidade.setText("Cidade");

        buttonGroup1.add(rButtonShowAll);
        rButtonShowAll.setText("Exibir Tudo");
        rButtonShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonShowAllActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setText("Filtrar pelo E-mail");

        buttonGroup1.add(btnExp);
        btnExp.setText("Listar por Experiência");

        buttonGroup1.add(btnInfo);
        btnInfo.setText("Listar Informações do Candidato");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        jLabel3.setText("Digitar e-mail");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnCidade)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCidade))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnCurso)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)
                            .addComponent(rButtonShowAll))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(btnExp)
                            .addComponent(btnInfo)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(btnListCandidatos)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCurso)
                            .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCidade)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(rButtonShowAll))
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnListCandidatos)
                .addContainerGap())
        );

        jTCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sobrenome", "E-mail", "Residência", "Formação", "Habilidades", "Experiência1", "Experiência2", "Experiência3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTCandidatos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(620, 504));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCursoActionPerformed

    private void btnListCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCandidatosActionPerformed
        
    }//GEN-LAST:event_btnListCandidatosActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCursoActionPerformed

    private void rButtonShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonShowAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rButtonShowAllActionPerformed

    private void btnListCandidatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListCandidatosMouseClicked
        // TODO add your handling code here:
        ArrayList<String> candidatos;
        try {
            
            if (btnCurso.isSelected()){
                String coluna = "formacao";
                DefaultTableModel dtmCandidatos = (DefaultTableModel)jTCandidatos.getModel();
                dtmCandidatos.setNumRows(0);
                candidatos = servico.getPessoasFrom(coluna, txtCurso.getText());
                for (int i = 0; i < candidatos.size(); i=i+9) {
                    Object[] dados = {candidatos.get(i), candidatos.get(i+1), candidatos.get(i+2), candidatos.get(i+3), candidatos.get(i+4), candidatos.get(i+5), candidatos.get(i+6), candidatos.get(i+7), candidatos.get(i+8)};
                    dtmCandidatos.addRow(dados);
                }
            }
            
            else if (btnCidade.isSelected()){
                String coluna = "residencia";
                DefaultTableModel dtmCandidatos = (DefaultTableModel)jTCandidatos.getModel();
                dtmCandidatos.setNumRows(0);
                candidatos = servico.getPessoasFrom(coluna, txtCidade.getText());
                for (int i = 0; i < candidatos.size(); i=i+9) {
                    Object[] dados = {candidatos.get(i), candidatos.get(i+1), candidatos.get(i+2), candidatos.get(i+3), candidatos.get(i+4), candidatos.get(i+5), candidatos.get(i+6), candidatos.get(i+7), candidatos.get(i+8)};
                    dtmCandidatos.addRow(dados);
                }
            }
            
            else if (btnExp.isSelected()){
                String coluna = "email";
                DefaultTableModel dtmCandidatos = (DefaultTableModel)jTCandidatos.getModel();
                dtmCandidatos.setNumRows(0);
                candidatos = servico.getPessoasFrom(coluna, txtEmail.getText());
                for (int i = 0; i < candidatos.size(); i=i+9) {
                    Object[] dados = {"", "", "", "", "", "", candidatos.get(i+6), candidatos.get(i+7), candidatos.get(i+8)};
                    dtmCandidatos.addRow(dados);
                }
            }
            
            else if (btnInfo.isSelected()){
                String coluna = "email";
                DefaultTableModel dtmCandidatos = (DefaultTableModel)jTCandidatos.getModel();
                dtmCandidatos.setNumRows(0);
                candidatos = servico.getPessoasFrom(coluna, txtEmail.getText());
                for (int i = 0; i < candidatos.size(); i=i+9) {
                    Object[] dados = {candidatos.get(i), candidatos.get(i+1), candidatos.get(i+2), candidatos.get(i+3), candidatos.get(i+4), candidatos.get(i+5), candidatos.get(i+6), candidatos.get(i+7), candidatos.get(i+8)};
                    dtmCandidatos.addRow(dados);
                }
            }

            else if (rButtonShowAll.isSelected()) {              
                DefaultTableModel dtmCandidatos = (DefaultTableModel)jTCandidatos.getModel();
                dtmCandidatos.setNumRows(0);
                candidatos = servico.getPessoas();
                for (int i = 0; i < candidatos.size(); i=i+9) {
                    Object[] dados = {candidatos.get(i), candidatos.get(i+1), candidatos.get(i+2), candidatos.get(i+3), candidatos.get(i+4), candidatos.get(i+5), candidatos.get(i+6), candidatos.get(i+7), candidatos.get(i+8)};
                    dtmCandidatos.addRow(dados);
                }
            }
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(null, "Erro: "+ ex.getMessage());
        }
    }//GEN-LAST:event_btnListCandidatosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cliente dialog = new Cliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnCidade;
    private javax.swing.JRadioButton btnCurso;
    private javax.swing.JRadioButton btnExp;
    private javax.swing.JRadioButton btnInfo;
    private javax.swing.JButton btnListCandidatos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTCandidatos;
    private javax.swing.JRadioButton rButtonShowAll;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
